Repository codeit-intermediate-project/taskify, pull requests merged in 2024-09, with the labels that each got.

#5 TASK-43: 대시보드 페이지 컴포넌트, 레이아웃 구성 및 퍼블리싱
  src/app/dashboard/[dashboardid]/page.tsx
  src/components/dashboard/AddColumnButton.tsx
  src/components/dashboard/Card.tsx
  src/components/dashboard/Column.tsx
  src/components/dashboard/ColumnList.tsx
  tsconfig.json
Labels: Feat, Design

#6 TASK-34: 내 대시보드 페이지, 퍼블리싱 및 컴포넌트 분리
  .husky/pre-commit
  package-lock.json
  package.json
  src/app/globals.css
  src/app/mydashboard/page.tsx
  src/app/page.tsx
  src/components/MyDashBoard/InvitedDashBoardList.tsx
  src/components/MyDashBoard/JoinedDashBoardList.tsx
  src/components/MyDashBoard/UI/InvitedDashBoard.tsx
  src/components/MyDashBoard/UI/NoInvitedDashBoard.tsx
  src/components/MyDashBoard/UI/Paigination.tsx
  src/components/MyDashBoard/UI/SearchForm.tsx
  tsconfig.json
Labels: Feat, Design

#9 TASK-51 : 대시보드 수정 페이지 컴포넌트 분리 및 퍼블리싱
  .husky/_/husky.sh
  public/icons/.gitkeep
  public/icons/add_box.png
  public/icons/add_purple.png
  public/icons/arrow_drop_down.png
  public/icons/arrow_left.png
  public/icons/arrow_right.png
  public/icons/calendar.png
  public/icons/checkbox_active.png
  public/icons/checkbox_inactive.png
  public/icons/crown.png
  public/icons/email.png
  public/icons/facebook.png
  public/icons/instagram.png
  public/icons/kebab.png
  public/icons/pencil.png
  public/icons/search.png
  public/icons/settings.png
  public/icons/visibility_off.png
  public/icons/visibility_on.png
  public/icons/x.png
  public/images/codeit_logo.png
  public/images/dashboard_empty.png
  public/images/landing1.png
  public/images/landing2.png
  public/images/landing3.png
  public/images/landing4.png
  public/images/landing5.png
  public/images/large_logo.png
  public/images/main_logo.png
  public/images/small_logo.png
  src/app/dashboard/[dashboardId]/dashboardEdit/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/dashboardEdit/EditDashboard.tsx
  src/components/dashboardEdit/InvitationList.tsx
  src/components/dashboardEdit/MemberList.tsx
  tsconfig.json
Labels: Feat, Design

#12 TASK-55: 헤더 에러 수정 & 사이드 바 구현 완료
  .eslintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  public/icons/check.png
  src/app/dashboard/[dashboardid]/layout.tsx
  src/app/dashboard/[dashboardid]/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/mydashboard/layout.tsx
  src/app/mydashboard/page.tsx
  src/app/mypage/layout.tsx
  src/app/page.tsx
  src/components/@shared/Common/AuthHeader.tsx
  src/components/@shared/Common/Input.tsx
  src/components/@shared/Common/SideBar.tsx
  src/components/@shared/Common/UnAuthHeader.tsx
  src/components/@shared/Layout/DashboardLayout.tsx
  src/components/@shared/UI/Button/Button.tsx
  src/components/@shared/UI/Button/PrimaryButton.tsx
  src/components/@shared/UI/Button/SecondaryButton.tsx
  src/core/api/postDashboard.ts
  src/core/contexts/DeviceContext.tsx
  src/core/contexts/RootContexts.tsx
  src/core/dtos/AuthDto.ts
  src/core/dtos/DashboardDto.ts
  src/lib/constants/themeConst.ts
  src/lib/hooks/useApi.tsx
  src/lib/utils/cn.ts
  src/middleware.ts
Labels: Feat, Chore

#10 TASK-50 : 페이지네이션
  .eslintrc.json
  .vscode/setting.json
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/edit/EditDashboard.tsx
  src/components/edit/InvitationList.tsx
  src/components/edit/MemberList.tsx
  src/components/edit/Pagination.tsx
  src/core/api/.gitkeep
  src/lib/hooks/usePaginavigation.ts
  tsconfig.json
Labels: Feat

#13 TASK-37: 내 대시보드 페이지, 페이지네이션 적용 및 검색 기능 추가
  .eslintrc.json
  .vscode/setting.json
  package-lock.json
  package.json
  postcss.config.mjs
  public/icons/back.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/mydashboard/page.tsx
  src/components/MyDashBoard/InvitedDashBoard.tsx
  src/components/MyDashBoard/InvitedDashBoardList.tsx
  src/components/MyDashBoard/JoinedDashBoardList.tsx
  src/components/MyDashBoard/UI/InviteHeader.tsx
  src/components/MyDashBoard/UI/InvitedDashBoard.tsx
  src/components/MyDashBoard/UI/NoDashBoard.tsx
  src/components/MyDashBoard/UI/Pagination.tsx
  src/components/MyDashBoard/UI/Paigination.tsx
  src/components/MyDashBoard/UI/ReturnButton.tsx
  src/components/MyDashBoard/UI/SearchForm.tsx
  src/core/api/.gitkeep
  src/core/api/apiCall.ts
  src/core/api/getDashboards.ts
  src/core/api/getInvitations.ts
  src/core/api/putInvitations.ts
  src/core/contexts/MyDashboardProvider.tsx
  src/core/dtos/DashboardsDto.ts
  src/core/dtos/InvitationsDto.ts
  src/lib/constants/initialValue.tsx
  src/lib/hooks/useApi.tsx
  src/lib/hooks/usePagination.tsx
  src/lib/hooks/useSearch.tsx
  tsconfig.json
Labels: Feat

#15 Task-86: 헤더 & 사이드바 리팩토링
  .eslintcache
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/mydashboard/page.tsx
  src/components/@shared/Common/AuthHeader.tsx
  src/components/@shared/Common/HeaderTitle.tsx
  src/components/@shared/Common/Logo.tsx
  src/components/@shared/Common/MembersProfile.tsx
  src/components/@shared/Common/Modals/DashBoardAddModal.tsx
  src/components/@shared/Common/SideBar.tsx
  src/components/@shared/Common/SideBarList.tsx
  src/components/@shared/Common/UnAuthHeader.tsx
  src/components/@shared/Common/UserProfile.tsx
  src/components/@shared/Layout/DashboardLayout.tsx
  src/components/@shared/UI/Button/LinkButton.tsx
  src/core/contexts/RootContexts.tsx
  src/lib/constants/initialValues.ts
  src/lib/hooks/useApi.ts
  src/lib/hooks/useDashBoardDetail.ts
  src/lib/hooks/useDashBoardMembers.ts
  src/lib/hooks/useDashBoards.ts
  tailwind.config.ts
Labels: Feat, Comment

#18 TASK-69 : 랜딩페이지 컴포넌트 분리 및 기본 퍼블리싱
  src/app/page.tsx
  src/components/Home/DescriptonCard.tsx
  src/components/Home/LandingBottom.tsx
  src/components/Home/LandingMain.tsx
  src/components/Home/LandingTop.tsx
  src/components/Home/PointCard.tsx
Labels: Feat, Design

#27 TASK-92: esLint 및 type 에러 수정
  src/app/mydashboard/layout.tsx
  src/components/MyDashBoard/InvitedDashBoard.tsx
  src/components/MyDashBoard/InvitedDashBoardList.tsx
  src/components/MyDashBoard/UI/CreateDashboardButton.tsx
  src/components/MyDashBoard/UI/DashboardCard.tsx
  src/components/MyDashBoard/UI/NoDashBoard.tsx
  src/components/MyDashBoard/UI/Pagination.tsx
  src/components/MyDashBoard/UI/ReturnButton.tsx
  src/components/MyDashBoard/UI/SearchForm.tsx
  src/core/dtos/DashboardsDto.ts
  src/core/dtos/InvitationsDto.ts
Labels: Fix

#22 TASK-89: 비밀번호 변경 기능
  .eslintcache
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/mydashboard/page.tsx
  src/app/mypage/page.tsx
  src/components/@shared/Common/AuthHeader.tsx
  src/components/@shared/Common/HeaderTitle.tsx
  src/components/@shared/Common/Inputs/FileInput.tsx
  src/components/@shared/Common/Inputs/Input.tsx
  src/components/@shared/Common/Logo.tsx
  src/components/@shared/Common/MembersProfile.tsx
  src/components/@shared/Common/Modals/DashBoardAddModal.tsx
  src/components/@shared/Common/Modals/PasswordEditModal.tsx
  src/components/@shared/Common/SideBar.tsx
  src/components/@shared/Common/SideBarList.tsx
  src/components/@shared/Common/UnAuthHeader.tsx
  src/components/@shared/Common/UserProfile.tsx
  src/components/@shared/Layout/DashboardLayout.tsx
  src/components/@shared/UI/Button/Button.tsx
  src/components/@shared/UI/Button/LinkButton.tsx
  src/components/@shared/UI/Button/PrimaryButton.tsx
  src/components/MyPage/PasswordEditCard.tsx
  src/components/MyPage/ProfileEditCard.tsx
  src/core/api/instance.ts
  src/core/api/postDashboard.ts
  src/core/api/postImageUpload.ts
  src/core/api/putMyProfile.ts
  src/core/api/putPassword.ts
  src/core/contexts/RootContexts.tsx
  src/core/dtos/AuthDto.ts
  src/core/dtos/CommonDto.ts
  src/lib/constants/initialValues.ts
  src/lib/hooks/useApi.ts
  src/lib/hooks/useDashBoardDetail.ts
  src/lib/hooks/useDashBoardMembers.ts
  src/lib/hooks/useDashBoards.ts
  tailwind.config.ts
Labels: Feat, Rename, Comment

#25 TASK-76 : 회원가입, 로그인 페이지 구현 및 유효성 검사 기능 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/components/Home/DescriptionCard.tsx
  src/components/Home/LandingBottom.tsx
  src/components/Home/LandingMain.tsx
  src/components/Home/LandingTop.tsx
  src/components/Home/PointCard.tsx
  src/components/auth/auth.tsx
Labels: Feat, Design, Refactor

#31 TASK-42: 반응형 디자인 적용, 모바일 사이즈 기준
  src/app/mydashboard/page.tsx
  src/components/MyDashBoard/InvitedDashboard.tsx
  src/components/MyDashBoard/InvitedDashboardList.tsx
  src/components/MyDashBoard/JoinedDashboardList.tsx
  src/components/MyDashBoard/UI/AcceptButton.tsx
  src/components/MyDashBoard/UI/DashboardCard.tsx
  src/components/MyDashBoard/UI/InviteHeader.tsx
  src/components/MyDashBoard/UI/NoDashboard.tsx
  src/components/MyDashBoard/UI/SearchForm.tsx
Labels: Design

#34 TASK-52: 리팩토링 & 수정된 페이지네이션 적용
  src/components/MyDashBoard/InvitedDashboard.tsx
  src/components/MyDashBoard/InvitedDashboardList.tsx
  src/components/MyDashBoard/JoinedDashboardList.tsx
  src/components/MyDashBoard/UI/DashboardCard.tsx
  src/components/MyDashBoard/UI/Pagination.tsx
  src/core/contexts/MyDashboardContext.tsx
  src/core/dtos/DashboardsDto.ts
  src/lib/constants/dashboardsInit.ts
  src/lib/constants/invitationsInit.ts
  src/lib/hooks/useGetInvitations.ts
  src/lib/hooks/useHandleInvitationResponse.ts
  src/lib/hooks/useInvitationsList.ts
  src/lib/hooks/usePagination.ts
Labels: Fix, Refactor

#38 [main]: actions 업데이트, git-push-main.yml 재생성
  .github/workflows/git-push-main.yml
Labels: Fix

#40 Feat: 카드, 컬럼 수정시 데이터 같으면 패칭 방지
  .eslintrc.json
  .github/workflows/git-push-main.yml
  .vscode/settings.json
  build.sh
  package-lock.json
  package.json
  src/components/@shared/Common/Modals/DashboardAddModal.tsx
  src/components/Modals/CardDetailModal.tsx
  src/components/Modals/CreateCardModal.tsx
  src/components/Modals/EditCardModal.tsx
  src/components/MyDashBoard/UI/NoDashboard.tsx
  src/components/dashboard/CardDetailComment.tsx
  src/components/dashboard/UI/Card.tsx
  src/core/contexts/DashBoardContext.tsx
  src/lib/hooks/.gitkeep
  src/lib/hooks/useCards.ts
  src/lib/hooks/useColumns.ts
  src/lib/hooks/useComments.ts
  src/lib/utils/convertStringToColor.ts
  src/lib/utils/convertStringToColorHex.ts
  src/lib/utils/convertStringToRGBA.ts
Labels: Feat, Fix

#42 TASK-75: 타입 오류 및 기타 오류 해결
  package-lock.json
  package.json
  src/app/login/page.tsx
  src/app/mydashboard/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/components/Auth/AuthModal.tsx
  src/components/Auth/AuthPage.tsx
  src/components/Auth/InputField.tsx
  src/components/auth/auth.tsx
  src/core/contexts/RootContexts.tsx
  src/core/dtos/AuthDto.ts
  src/lib/hooks/useApi.ts
Labels: Fix

#46 TASK-98: 1차 QA 반영
  src/components/@shared/Common/Modals/DashboardAddModal.tsx
  src/components/@shared/UI/Button/SecondaryButton.tsx
  src/components/Auth/AuthPage.tsx
  src/components/MyDashBoard/InvitedDashboardList.tsx
  src/components/MyDashBoard/UI/AcceptButton.tsx
  src/components/MyDashBoard/UI/Pagination.tsx
Labels: Design

#45 TASK-33: 1차 QA 반영
  src/app/dashboard/[dashboardid]/edit/page.tsx
  src/components/edit/DeleteModal.tsx
  src/components/edit/EditDashboard.tsx
  src/components/edit/InvitationList.tsx
  src/components/edit/MemberList.tsx
Labels: Feat

#48 TASK-99: 작성자 기준 대시보드 분류 및 목록화 & UI 개선
  package-lock.json
  package.json
  src/components/MyDashBoard/DashboardGroup.tsx
  src/components/MyDashBoard/InvitedDashboardList.tsx
  src/components/MyDashBoard/JoinedDashboardList.tsx
  src/components/MyDashBoard/UI/DashboardCard.tsx
  src/components/MyDashBoard/UI/Pagination.tsx
  src/core/contexts/MyDashboardContext.tsx
  src/lib/hooks/useCategorizedDashboards.ts
  src/lib/hooks/useCountItems.ts
  src/lib/hooks/useResize.ts
Labels: Feat, Design

#50 TASK-84: 무한스크롤 로직 수정 & 초대 응답 토스트 UI 적용
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/MyDashBoard/InvitedDashboardList.tsx
  src/lib/hooks/useGetInvitations.ts
  src/lib/hooks/useHandleInvitationResponse.ts
  src/lib/hooks/useInfiniteScroll.ts
Labels: Design, Refactor

#49 TASK-75: 랜딩페이지 반응형 구현 및 모달창 디자인 구현
  public/images/landing_top.png
  src/components/Auth/AuthModal.tsx
  src/components/Home/DescriptionCard.tsx
  src/components/Home/LandingBottom.tsx
  src/components/Home/LandingMain.tsx
  src/components/Home/LandingTop.tsx
  src/components/Home/PointCard.tsx
  tailwind.config.ts
Labels: Design

#52 TASK-106: 대시보드 페이지 리팩토링 및 여러가지 구현
  src/app/dashboard/[dashboardid]/page.tsx
  src/app/globals.css
  src/components/Modals/CardDetailModal.tsx
  src/components/Modals/CreateCardModal.tsx
  src/components/Modals/CreateColumnModal.tsx
  src/components/Modals/EditCardModal.tsx
  src/components/Modals/EditColumnModal.tsx
  src/components/dashboard/CardDetailComment.tsx
  src/components/dashboard/ColumnList.tsx
  src/components/dashboard/UI/AddColumnButton.tsx
  src/components/dashboard/UI/Card.tsx
  src/components/dashboard/UI/Column.tsx
  src/components/dashboard/UI/DashboardSideMenu.tsx
  src/components/dashboard/UI/FloatingColumnList.tsx
  src/core/api/cardApis.ts
  src/core/api/comments.ts
  src/core/contexts/DashboardContext.tsx
  src/core/contexts/DashboardSideMenuContext.tsx
  src/core/dtos/CardsDto.ts
  src/core/dtos/CommentsDto.ts
  src/lib/hooks/useCards.ts
  src/lib/hooks/useColumns.ts
  src/lib/hooks/useComments.ts
  src/lib/hooks/useInfiniteScroll.ts
  src/lib/hooks/useScrollToColumn.ts
  src/lib/utils/formatDDay.ts
  src/lib/utils/notifications/showErrorNotification.ts
  src/lib/utils/notifications/showSuccessNotification.ts
Labels: Feat, Design, Fix, Refactor

#53 [main]: 추가 기능 병합
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  public/images/landing_top.png
  src/app/dashboard/[dashboardid]/page.tsx
  src/app/globals.css
  src/components/@shared/Common/AuthHeader.tsx
  src/components/@shared/UI/PurpleAddIcon.tsx
  src/components/@shared/animations/GradientFrame.tsx
  src/components/@shared/animations/Rotate.tsx
  src/components/@shared/animations/SlideInList.tsx
  src/components/@shared/animations/SlideRight.tsx
  src/components/Auth/AuthModal.tsx
  src/components/Home/DescriptionCard.tsx
  src/components/Home/LandingBottom.tsx
  src/components/Home/LandingMain.tsx
  src/components/Home/LandingTop.tsx
  src/components/Home/PointCard.tsx
  src/components/Modals/CardDetailModal.tsx
  src/components/Modals/CreateCardModal.tsx
  src/components/Modals/CreateColumnModal.tsx
  src/components/Modals/EditCardModal.tsx
  src/components/Modals/EditColumnModal.tsx
  src/components/MyDashBoard/DashboardGroup.tsx
  src/components/MyDashBoard/InvitedDashboardList.tsx
  src/components/MyDashBoard/JoinedDashboardList.tsx
  src/components/MyDashBoard/UI/AcceptButton.tsx
  src/components/MyDashBoard/UI/CreateDashboardButton.tsx
  src/components/MyDashBoard/UI/DashboardCard.tsx
  src/components/MyDashBoard/UI/Pagination.tsx
  src/components/MyDashBoard/UI/SearchForm.tsx
  src/components/dashboard/CardDetailComment.tsx
  src/components/dashboard/ColumnList.tsx
  src/components/dashboard/UI/AddColumnButton.tsx
  src/components/dashboard/UI/Card.tsx
  src/components/dashboard/UI/Column.tsx
  src/components/dashboard/UI/DashboardSideMenu.tsx
  src/components/dashboard/UI/FloatingColumnList.tsx
  src/core/api/cardApis.ts
  src/core/api/comments.ts
  src/core/contexts/DashboardContext.tsx
  src/core/contexts/DashboardSideMenuContext.tsx
  src/core/contexts/MyDashboardContext.tsx
  src/core/dtos/CardsDto.ts
  src/core/dtos/CommentsDto.ts
  src/lib/hooks/useCards.ts
  src/lib/hooks/useCategorizedDashboards.ts
  src/lib/hooks/useColumns.ts
  src/lib/hooks/useComments.ts
  src/lib/hooks/useCountItems.ts
  src/lib/hooks/useGetInvitations.ts
  src/lib/hooks/useHandleInvitationResponse.ts
  src/lib/hooks/useInfiniteScroll.ts
  src/lib/hooks/useResize.ts
  src/lib/hooks/useScrollToColumn.ts
  src/lib/utils/formatDDay.ts
  src/lib/utils/notifications/showErrorNotification.ts
  src/lib/utils/notifications/showSuccessNotification.ts
  tailwind.config.ts
Labels: Test

#54 TASK-33 : 대시보드 수정 페이지 리팩토링
  package-lock.json
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/app/dashboard/[dashboardid]/edit/page.tsx
  src/app/layout.tsx
  src/components/@shared/Common/HeaderInviteModal.tsx
  src/components/edit/DeleteModal.tsx
  src/components/edit/EditDashboard.tsx
  src/components/edit/InvitationList.tsx
  src/components/edit/InviteModal.tsx
  src/components/edit/MemberList.tsx
  src/components/edit/Pagination.tsx
Labels: Design, Refactor

#55 TASK-75 : 랜딩페이지 애니메이션 구현
  src/app/page.tsx
  src/components/Home/LandingTop.tsx
Labels: Feat, Design

#56 TASK-108: 사이드바 애니메이션 & 페이지네이션 디자인 수정
  package-lock.json
  package.json
  src/components/@shared/Common/AuthHeader.tsx
  src/components/@shared/Common/SideBar.tsx
  src/components/@shared/Common/SideBarList.tsx
  src/components/@shared/Common/SideBarPagination.tsx
  src/components/@shared/animations/SlideInList.tsx
Labels: Design

#57 TASK-109: not-found 페이지
  package-lock.json
  package.json
  public/icons/document_empty.svg
  public/icons/house.png
  src/app/not-found.tsx
Labels: Feat, Design

#59 TASK-112: 참여중인 대시보드가 없는 경우 처리
  public/icons/add_dashboard.svg
  src/components/@shared/Common/HeaderInviteModal.tsx
  src/components/@shared/Common/SideBarList.tsx
  src/components/MyDashBoard/DashboardGroup.tsx
Labels: Design
